package Practice_30X;
public enum DrinkTypeEnum
{
    BEER, WINE, VODKA, BRANDY, CHAMPAGNE, WHISKY, TEQUILA,
    RUM,VERMUTH,LIQUOR, JAGERMEISTER, JUICE,COFEE, GREEN_TEA,
    BLACK_TEA, MILK, WATER, SODA
}
